common: &common
  adapter: postgresql
  host: localhost

development:
  <<: *common
  database: boilerplate_development

test:
  <<: *common
  database: boilerplate_test

production:
  <<: *common
  database: boilerplate_production